name: CustumItems
main: crystal/Main
api: 3.0.0
author: secretsiver313
version: 1.0.0
description: Custom items for secretsilvers server
commands:
  hc:
    default: op
    permission: secret.hc.use
    description: Gives you a Health Crystal
